triggers:
  github_push: true
  cron: "@daily"
clean_workspace: true

extra_jobs:
  - name: docker-jenkins-maven-job
    docker_name: sunet/docker-jenkins-maven-job
    docker_context_dir: maven
  - name: docker-jenkins-node-job
    docker_name: sunet/docker-jenkins-node-job
    docker_context_dir: node
  - name: docker-jenkins-golang-job
    docker_name: sunet/docker-jenkins-golang-job
    docker_context_dir: golang
  - name: docker-jenkins-job-xenial
    docker_name: sunet/docker-jenkins-job-xenial
    docker_context_dir: xenial
  - name: docker-jenkins-job-python3.9
    docker_name: sunet/docker-jenkins-job-python3.9
    docker_context_dir: python3.9
